version: '3.4'

networks:
  xodoapp:

services:
  xodoappdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 8002:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=12345678Ed
    networks:
        - xodoapp

  xodoapp.webapi:
    image: ${DOCKER_REGISTRY-}xodoappwebapi
    build:
      context: .
      dockerfile: XodoApp.WebApi/Dockerfile
    ports:
        - 8001:8080
    depends_on:
        - xodoappdb
    networks:
        - xodoapp
